# Generated by Django 2.2.7 on 2019-11-25 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='voluntario', max_length=10)),
                ('rut', models.CharField(default='12345678-9', max_length=12)),
                ('fechanacimiento', models.DateField(default=django.utils.timezone.now)),
                ('telefono', models.PositiveIntegerField(default=0)),
                ('region', models.CharField(choices=[('', 'Seleccionar'), ('RM', 'Region Metropolitana'), ('AP', 'Arica y Parinacota'), ('TA', 'Tarapacá'), ('AN', 'Antofagasta'), ('AT', 'Atacama'), ('CO', 'Coquimbo'), ('VA', 'Valparaiso'), ('OH', "O'higgins"), ('MA', 'Maule'), ('NB', 'Ñuble'), ('BI', 'Biobío'), ('AR', 'La Araucanía'), ('LR', 'Los Ríos'), ('LL', 'Los Lagos'), ('AI', 'Aysén'), ('MG', 'Magallanes')], default='RM', max_length=50)),
                ('ciudad', models.CharField(choices=[('', 'Seleccionar'), ('AN', 'Antofagasta'), ('AR', 'Arica'), ('BU', 'Buin'), ('CA', 'Calama'), ('CH', 'Chillán'), ('CO', 'Colina'), ('CC', 'Concepción'), ('CP', 'Copiapó'), ('CY', 'Coyhaique'), ('CU', 'Curicó'), ('IQ', 'Iquique'), ('LS', 'La Serena'), ('LI', 'Limache'), ('LN', 'Linares'), ('LA', 'Los Andes'), ('LG', 'Los Ángeles'), ('ME', 'Melipilla'), ('OS', 'Osorno'), ('OV', 'Ovalle'), ('PE', 'Peñaflor'), ('PM', 'Puerto Montt'), ('PA', 'Punta Arenas'), ('QU', 'Quillota'), ('RA', 'Rancagua'), ('ST', 'Santiago'), ('SA', 'San Antonio'), ('SB', 'San Bernardo'), ('SF', 'San Felipe'), ('TA', 'Talagante'), ('TC', 'Talca'), ('TE', 'Temuco'), ('VA', 'Valdivia'), ('VP', 'Valparaíso')], default='ST', max_length=50)),
                ('tipovivienda', models.CharField(choices=[('', 'Seleccionar'), ('CS1', 'Casa con patio grande'), ('CS2', 'Casa con patio pequeño'), ('CS3', 'Casa sin patio'), ('DTO', 'Departamento')], default='CS3', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
